FROM python:3.8.3-alpine

WORKDIR /usr/src/app

# Prevent Python from writing pyc files to disc
ENV PYTHONDONTWRITEBYTECODE 1
# Prevent Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /usr/src/app/requirements.txt

RUN set -eux \
  && apk add --no-cache --virtual .build-deps build-base \
    libressl-dev libffi-dev gcc musl-dev python3-dev postgresql-dev \
  && pip install --upgrade pip setuptools wheel \
  && pip install -r /usr/src/app/requirements.txt \
  && rm -rf /root/.cache/pip

COPY . /usr/src/app/
